# Generated by Django 3.2.8 on 2021-10-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=128)),
                ('sensor_id', models.IntegerField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
